// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package user

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      string
	Email     string
	Bio       string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
